/**
 * Migration Script: Fix Global Styles organizationId
 *
 * This script updates all styles that were generated by the seed service
 * to have organizationId = null, making them properly global styles.
 *
 * Run with: npx tsx scripts/fix-global-styles-organization-id.ts
 */

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function fixGlobalStyles() {
  console.log('🔍 Finding styles generated by AI seed service...')

  try {
    // Find all styles - we'll filter in JavaScript since MongoDB composite queries are limited
    const allStyles = await prisma.style.findMany({
      where: {
        organizationId: { not: null }, // Has an organizationId but shouldn't
      },
      select: {
        id: true,
        slug: true,
        name: true,
        organizationId: true,
        metadata: true,
      },
    })

    // Filter in JavaScript for AI-generated styles
    const stylesToFix = allStyles.filter((style: any) => {
      return style.metadata?.aiGenerated === true
    })

    console.log(`📊 Found ${stylesToFix.length} AI-generated styles to fix`)

    if (stylesToFix.length === 0) {
      console.log('✅ All AI-generated styles already have organizationId = null')
      return
    }

    // Display styles that will be updated
    console.log('\n📝 Styles to update:')
    stylesToFix.forEach((style: any, index: number) => {
      console.log(`  ${index + 1}. ${style.name.en} (${style.slug})`)
      console.log(`     Current organizationId: ${style.organizationId}`)
    })

    console.log('\n🔄 Updating styles to organizationId = null...')

    // Update each style individually
    let updatedCount = 0
    for (const style of stylesToFix) {
      await prisma.style.update({
        where: { id: style.id },
        data: { organizationId: null },
      })
      updatedCount++
    }

    console.log(`\n✅ Successfully updated ${updatedCount} styles`)
    console.log('🎉 All AI-generated styles are now properly global!')
    console.log('\n📋 Next steps:')
    console.log('   1. Refresh the admin styles page')
    console.log('   2. You should now see all generated styles')
    console.log('   3. Future seed operations will automatically create global styles')

  } catch (error) {
    console.error('❌ Error fixing global styles:', error)
    throw error
  } finally {
    await prisma.$disconnect()
  }
}

// Run the migration
fixGlobalStyles()
  .then(() => {
    console.log('\n✨ Migration completed successfully')
    process.exit(0)
  })
  .catch((error) => {
    console.error('\n💥 Migration failed:', error)
    process.exit(1)
  })
